version: "3.7"

services:
  php:
    container_name: php
    build:
      context: ./docker/php
      # dockerfile: Dockerfile
    restart: unless-stopped # 異常終了時に自動再起動
    volumes:
      - ./laravelapi:/var/www

  nginx:
    # 使用するimage。Dockerfileを使用しないserviceはここでimageを指定する。
    # image: nginx # Dockerfileに転記
    container_name: nginx
    build:
      context: ./docker/nginx
      # dockerfile: Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./laravelapi:/var/www
      # /etc/nginx/conf.d にある拡張子confのfileが設定fileとして読み込まれる。
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # 依存関係。phpコンテナを起動してから、nginxコンテナを起動する。
    depends_on:
      - php

  db:
    # image: mysql:5.7 # Dockerfileに転記
    container_name: mysql-host
    build:
      context: ./docker/db
      # dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: unless-stopped
    # 環境変数を定義。
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: docker
      MYSQL_PASSWORD: dockerp
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # !!!!! WARNING !!!!!
      # aws利用時は、DBはRDSを利用するよう設定変更。
      # - mysql_volume:/var/lib/mysql # 名前付きvolumeを使用。
      - ./docker/db/data:/var/lib/mysql # ホストのdirとbind。
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d # 初回のsql file実行dir。データの移行時などに利用。

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-host # dbサービスのcontainer_name
      - PMA_USER=root
      - PMA_PASSWORD=rootp
    # linkさせるサービス名を指定。
    links:
      - db

# volumes: # 名前付きvolumeの作成のため、top階層で名前を指定。
#   mysql_volume:
